# Write a program to input eight numbers from the user and display all the unique number (once)
s = set() # we used set() to create a empty set.
n = int(input("enter the number: "))
s.add(n)
n = int(input("enter the number: "))
s.add(n)
n = int(input("enter the number: "))
s.add(n)
n = int(input("enter the number: "))
s.add(n)
n = int(input("enter the number: "))
s.add(n)
n = int(input("enter the number: "))
s.add(n)
n = int(input("enter the number: "))
s.add(n)
n = int(input("enter the number: "))
s.add(n)

print(s)
